---
- hosts: localhost
  connection: local

  tasks:
    - name: collect instances_ids
      ec2_instance_facts:
        filters:
          "tag:Name": ansible
      register: ec2

    - debug:
        var: ec2.instances.0.instance_id.stdout

    - name: terminate existing ec2 VMs
      ec2:
        region: "us-east-1"
        state: 'absent'
        instance_ids: "{{ item }}"
      with_items: ec2.instances.0.instance_id
